#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Bash script that will display information about subdomains.

function domain_info {
	domain_names=("www" "lb-01" "web-01" "web-02")

	for i in "${domain_names[@]}";
	do
		dig "${i}"."$1" | grep -A1 'ANSWER SECTION:' | \
		awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$i"
	done
}

function subdomain_info {
	dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
	awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

if [ $# -lt 1 ]
then
	echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
	domain_info "$1";
else
	subdomain_info "$1" "$2";
fi
